version: '3.8'

services:
  flask_app:
    build:
      context: ./photo_service
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - /var/www/tigers-bot/photos:/app/photos
        #- /var/www/tigers-bot/photos_info.json:/app/photos_info.json
    environment:
      - RELOAD_VECTORS=${RELOAD_VECTORS:-false}
    depends_on:
      - qdrant
    networks:
      - bot_network

  telegram_bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    depends_on:
      - flask_app
    networks:
      - bot_network

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - /var/www/tigers-bot/qdrant:/qdrant/storage
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

volumes:
  qdrant_data:
